name: Deploy helpdesk to prod
on:
  push:
    branches:
      - 'main'

jobs:
  main_deploy:

    runs-on: ubuntu-latest
    environment: Main
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.MAINNET_ROLE_ARN }}
        aws-region: 'us-east-1'

    - name: Deploy site to S3
      run: |
        aws s3 sync --exclude "*.git/*" --exclude "*.github/*" --exclude "*.gitignore" --exclude "*.gitattributes" --exclude "README.md" --delete --only-show-errors . ${{ secrets.MAINNET_S3_BUCKET }}


    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.MAINNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
